import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";

import type { TestCase, TestDataItem } from "./types.js";
import type { TestCaseHistoryRecord } from "./projectTypes.js";

export type ExportFormat = "excel" | "pdf";

function totalCases(record: TestCaseHistoryRecord) {
  return record.output.positive.length + record.output.negative.length + record.output.edge.length;
}

function addWorksheetHeader(worksheet: ExcelJS.Worksheet) {
  worksheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } };
  worksheet.getRow(1).fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FF1F2937" },
  };
  worksheet.getRow(1).alignment = { vertical: "middle" };
  worksheet.views = [{ state: "frozen", ySplit: 1 }];
}

function autoFitColumns(worksheet: ExcelJS.Worksheet) {
  worksheet.columns.forEach((column) => {
    let width = 12;
    column.eachCell?.({ includeEmpty: true }, (cell) => {
      width = Math.max(width, String(cell.value ?? "").slice(0, 80).length + 2);
    });
    column.width = Math.min(width, 60);
  });
}

function addCaseRows(worksheet: ExcelJS.Worksheet, record: TestCaseHistoryRecord, cases: TestCase[]) {
  cases.forEach((testCase) => {
    worksheet.addRow({
      projectName: record.projectName,
      moduleName: record.moduleName,
      requirementTitle: record.requirementTitle,
      version: `Version ${record.version}`,
      testCaseId: testCase.id,
      testScenario: `${testCase.title}\n\nSteps:\n${testCase.steps.join("\n")}`,
      expectedResult: testCase.expected,
      priority: testCase.priority,
    });
  });
}

function addDataRows(worksheet: ExcelJS.Worksheet, record: TestCaseHistoryRecord, items: TestDataItem[]) {
  items.forEach((item) => {
    worksheet.addRow({
      projectName: record.projectName,
      moduleName: record.moduleName,
      requirementTitle: record.requirementTitle,
      version: `Version ${record.version}`,
      dataType: item.field,
      exampleValue: [...item.valid, ...item.invalid, ...item.boundary].join(", "),
      description: `Valid: ${item.valid.join(", ")}\nInvalid: ${item.invalid.join(", ")}\nBoundary: ${item.boundary.join(", ")}`,
    });
  });
}

function styleWorkbook(workbook: ExcelJS.Workbook) {
  workbook.eachSheet((worksheet) => {
    addWorksheetHeader(worksheet);
    worksheet.eachRow((row) => {
      row.alignment = { vertical: "top", wrapText: true };
    });
    autoFitColumns(worksheet);
  });
}

export async function buildExcelExport(records: TestCaseHistoryRecord[]) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "AI QA Copilot";
  workbook.created = new Date();

  const summary = workbook.addWorksheet("Summary");
  summary.columns = [
    { header: "Project Name", key: "projectName" },
    { header: "Module Name", key: "moduleName" },
    { header: "Requirement Title", key: "requirementTitle" },
    { header: "Version", key: "version" },
    { header: "Generated Date", key: "generatedDate" },
    { header: "Generated By", key: "generatedBy" },
    { header: "AI Model Used", key: "aiModelUsed" },
    { header: "Coverage Score", key: "coverageScore" },
    { header: "Status", key: "status" },
  ];
  records.forEach((record) => {
    summary.addRow({
      projectName: record.projectName,
      moduleName: record.moduleName,
      requirementTitle: record.requirementTitle,
      version: `Version ${record.version}`,
      generatedDate: record.generatedAt,
      generatedBy: record.generatedBy,
      aiModelUsed: record.aiModelUsed,
      coverageScore: `${record.coverageScore}%`,
      status: record.status,
    });
  });

  const caseColumns = [
    { header: "Project Name", key: "projectName" },
    { header: "Module Name", key: "moduleName" },
    { header: "Requirement Title", key: "requirementTitle" },
    { header: "Version", key: "version" },
    { header: "Test Case ID", key: "testCaseId" },
    { header: "Test Scenario", key: "testScenario" },
    { header: "Expected Result", key: "expectedResult" },
    { header: "Priority", key: "priority" },
  ];
  const positive = workbook.addWorksheet("Positive Test Cases");
  const negative = workbook.addWorksheet("Negative Test Cases");
  const edge = workbook.addWorksheet("Edge Cases");
  positive.columns = caseColumns;
  negative.columns = caseColumns;
  edge.columns = caseColumns.filter((column) => column.key !== "priority");

  const testData = workbook.addWorksheet("Test Data Suggestions");
  testData.columns = [
    { header: "Project Name", key: "projectName" },
    { header: "Module Name", key: "moduleName" },
    { header: "Requirement Title", key: "requirementTitle" },
    { header: "Version", key: "version" },
    { header: "Data Type", key: "dataType" },
    { header: "Example Value", key: "exampleValue" },
    { header: "Description", key: "description" },
  ];

  const criteria = workbook.addWorksheet("Acceptance Criteria");
  criteria.columns = [
    { header: "Project Name", key: "projectName" },
    { header: "Requirement Title", key: "requirementTitle" },
    { header: "Version", key: "version" },
    { header: "Criteria ID", key: "criteriaId" },
    { header: "Description", key: "description" },
  ];

  const playwright = workbook.addWorksheet("Playwright Test Skeleton");
  playwright.columns = [
    { header: "Project Name", key: "projectName" },
    { header: "Requirement Title", key: "requirementTitle" },
    { header: "Version", key: "version" },
    { header: "Generated Code", key: "code" },
  ];

  records.forEach((record) => {
    addCaseRows(positive, record, record.output.positive);
    addCaseRows(negative, record, record.output.negative);
    addCaseRows(edge, record, record.output.edge);
    addDataRows(testData, record, record.output.testData);
    record.output.acceptanceCriteria.forEach((item, index) => {
      criteria.addRow({
        projectName: record.projectName,
        requirementTitle: record.requirementTitle,
        version: `Version ${record.version}`,
        criteriaId: `AC-${String(index + 1).padStart(2, "0")}`,
        description: item,
      });
    });
    playwright.addRow({
      projectName: record.projectName,
      requirementTitle: record.requirementTitle,
      version: `Version ${record.version}`,
      code: record.output.playwright,
    });
  });

  styleWorkbook(workbook);
  return Buffer.from(await workbook.xlsx.writeBuffer());
}

function addPdfSection(doc: PDFKit.PDFDocument, title: string) {
  doc.moveDown(1);
  doc.fontSize(15).fillColor("#111827").text(title, { underline: true });
  doc.moveDown(0.5).fontSize(10).fillColor("#111827");
}

function addPdfCases(doc: PDFKit.PDFDocument, cases: TestCase[]) {
  cases.forEach((testCase) => {
    doc.font("Helvetica-Bold").text(`${testCase.id} - ${testCase.title} (${testCase.priority})`);
    doc.font("Helvetica").text(`Expected: ${testCase.expected}`);
    doc.text(`Steps: ${testCase.steps.join(" | ")}`);
    doc.moveDown(0.5);
  });
}

function addPdfRecord(doc: PDFKit.PDFDocument, record: TestCaseHistoryRecord, isFirst: boolean) {
  if (!isFirst) doc.addPage();
  doc.font("Helvetica-Bold").fontSize(24).fillColor("#4F46E5").text("AI QA Copilot", { align: "center" });
  doc.moveDown(0.5).fontSize(18).fillColor("#111827").text("Test Case Export Report", { align: "center" });
  doc.moveDown(2);
  doc.fontSize(12).font("Helvetica");
  doc.text(`Project Name: ${record.projectName}`);
  doc.text(`Module Name: ${record.moduleName}`);
  doc.text(`Requirement Name: ${record.requirementTitle}`);
  doc.text(`Version Number: Version ${record.version}`);
  doc.text(`Generated Date: ${record.generatedAt}`);

  addPdfSection(doc, "1. Executive Summary");
  doc.text(`Coverage Score: ${record.coverageScore}%`);
  doc.text(`Total Test Cases: ${totalCases(record)}`);
  doc.text(`Total Positive Cases: ${record.output.positive.length}`);
  doc.text(`Total Negative Cases: ${record.output.negative.length}`);
  doc.text(`Total Edge Cases: ${record.output.edge.length}`);

  addPdfSection(doc, "2. Requirement Details");
  doc.text(record.requirementInput);

  addPdfSection(doc, "3. Acceptance Criteria");
  record.output.acceptanceCriteria.forEach((item, index) => doc.text(`AC-${index + 1}: ${item}`));

  addPdfSection(doc, "4. Positive Test Cases");
  addPdfCases(doc, record.output.positive);

  addPdfSection(doc, "5. Negative Test Cases");
  addPdfCases(doc, record.output.negative);

  addPdfSection(doc, "6. Edge Cases");
  addPdfCases(doc, record.output.edge);

  addPdfSection(doc, "7. Test Data Suggestions");
  record.output.testData.forEach((item) => {
    doc.text(`${item.field}: valid [${item.valid.join(", ")}], invalid [${item.invalid.join(", ")}], boundary [${item.boundary.join(", ")}]`);
  });

  addPdfSection(doc, "8. Playwright Test Skeleton");
  doc.font("Courier").fontSize(8).text(record.output.playwright, { lineGap: 1 });
  doc.font("Helvetica").fontSize(10);

  addPdfSection(doc, "9. Generation Information");
  doc.text(`Generated By: ${record.generatedBy}`);
  doc.text(`AI Model Used: ${record.aiModelUsed}`);
  doc.text(`Generated Date: ${record.generatedAt}`);
  doc.text(`Status: ${record.status}`);
}

export async function buildPdfExport(records: TestCaseHistoryRecord[]) {
  const doc = new PDFDocument({ margin: 48, size: "A4", bufferPages: true });
  const chunks: Buffer[] = [];

  doc.on("data", (chunk: Buffer) => chunks.push(chunk));
  const done = new Promise<Buffer>((resolve) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
  });

  records.forEach((record, index) => addPdfRecord(doc, record, index === 0));

  const range = doc.bufferedPageRange();
  for (let pageIndex = range.start; pageIndex < range.start + range.count; pageIndex += 1) {
    doc.switchToPage(pageIndex);
    doc.font("Helvetica").fontSize(8).fillColor("#6B7280").text(
      `Generated by AI QA Copilot - Page ${pageIndex + 1} of ${range.count}`,
      48,
      doc.page.height - 36,
      { align: "center" },
    );
  }

  doc.end();
  return done;
}
